//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareCenter2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareCenterEntities : DbContext
    {
        public CareCenterEntities()
            : base("name=CareCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Order> tb_Order { get; set; }
        public DbSet<tb_Pictuer> tb_Pictuer { get; set; }
        public DbSet<tb_Video> tb_Video { get; set; }
        public DbSet<tb_User> tb_User { get; set; }
        public DbSet<tb_MoneyRecord> tb_MoneyRecord { get; set; }
        public DbSet<tb_PartTime> tb_PartTime { get; set; }
        public DbSet<tb_Need> tb_Need { get; set; }
        public DbSet<tb_Comment> tb_Comment { get; set; }
        public DbSet<tb_Admins> tb_Admins { get; set; }
        public DbSet<tb_Context> tb_Context { get; set; }
    }
}
