//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareCenter2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Context
    {
        public string ContextID { get; set; }
        public string Title { get; set; }
        public string Explain { get; set; }
        public string Intro { get; set; }
        public string Type { get; set; }
        public int Status { get; set; }
        public string Memo { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
