//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareCenter2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PartTime
    {
        public string PartTimeID { get; set; }
        public string UserID { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public string Post { get; set; }
        public string SchoolName { get; set; }
        public string GraduationYear { get; set; }
        public string Education { get; set; }
        public string YearWork { get; set; }
        public string DateRange { get; set; }
        public string RoomService { get; set; }
        public string AgencyService { get; set; }
        public decimal Salary { get; set; }
        public int Status { get; set; }
        public string Memo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserName { get; set; }
    }
}
